Source : https://github.com/patrickloeber/pytorchTutorial/blob/master/02_tensor_basics.py

In [3]:
import torch

#Everything in Pytorch is based on Tensor operations.
# A tensor can have different dimensions
# so it can be 1d,2d or even 3d or higher

#sclar, vector,matrix, tensor

# torch.empty(size):uninitialized
x = torch.empty(1) # scalar
print(x,"\n")
x = torch.empty(3) #vector , 1D
print(x,"\n")
x = torch.empty(2,3) #matrix, 2D
print(x,"\n")
x = torch.empty(2,2,3) # tensor, 3 dimensions
print(x)
#x = torch.empty(2,2,2,3) #tensor, 4 dimensions

tensor([-1.4929e-30]) 

tensor([-1.4929e-30,  4.3554e-41,  7.0381e+17]) 

tensor([[3.4902e+18, 3.1392e-41, 3.2158e+18],
        [3.1392e-41, 4.4842e-44, 0.0000e+00]]) 

tensor([[[-1.4929e-30,  4.3554e-41,  2.4035e+18],
         [ 3.1392e-41,  4.4842e-44,  0.0000e+00]],

        [[ 1.1210e-43,  0.0000e+00,  8.0218e-16],
         [ 3.1399e-41,  0.0000e+00,  0.0000e+00]]])


In [4]:
#torch.rand(size) : random numbers [0,1]
x = torch.rand(5,3)
print(x)

tensor([[0.0633, 0.6734, 0.4144],
        [0.5780, 0.5210, 0.5425],
        [0.2788, 0.8518, 0.1574],
        [0.3653, 0.5870, 0.3855],
        [0.6881, 0.0846, 0.1268]])


In [5]:
#torch.zeros(size),fill with 0
#torch.ones(size), fill with 1

x = torch.zeros(5,3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [6]:
# check size
print(x.size())

torch.Size([5, 3])


In [7]:
#check data type
print(x.dtype)

torch.float32


In [8]:
#specify type, float32 default
x = torch.zeros(5,4,dtype=torch.float16)
print(x)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], dtype=torch.float16)


In [9]:
# check type
print(x.dtype)

torch.float16


In [10]:
# construct from data
x = torch.tensor([5,5,3])
print(x.size())

torch.Size([3])


In [20]:
# requires grad argument
# This will tell Pytorch that it will need to calculate the gradients for this tensor
# later in your optimization steps
#i.e this is a variable in your model that you want to optimize
x = torch.tensor([5.3,3],requires_grad=True)

# Operations
y = torch.rand(2,2)
x = torch.rand(2,2)

#element wise addition
print ("x",x)
print("y",y)
z = x + y
# torch.add(x,y)

#in place addition, everything with a trailing underscore is an inplace operations
#i.e it will modify the variable
y.add_(x)

print("y after add_","\n",y)

x tensor([[0.9949, 0.3099],
        [0.6878, 0.5453]])
y tensor([[0.8089, 0.2307],
        [0.1609, 0.7968]])
y after add_ 
 tensor([[1.8038, 0.5406],
        [0.8487, 1.3422]])


In [21]:
#subtraction
z = x -y
z = torch.sub(x,y)

#multiplication
z = x*y
z = torch.mul(x,y)

#division z = x/y
z = torch.div(x,y)

#slicing
x = torch.rand(5,3)

print(x)
print(x[:,0]) # all rows, column 0
print(x[1,:]) # row 1, all columns
print(x[1,1])

#get the actual value if only 1 element in your tensor
print(x[1,1].item())

tensor([[0.7959, 0.9449, 0.0042],
        [0.7288, 0.4176, 0.8589],
        [0.1365, 0.2373, 0.0164],
        [0.6706, 0.7589, 0.1178],
        [0.6434, 0.0038, 0.6667]])
tensor([0.7959, 0.7288, 0.1365, 0.6706, 0.6434])
tensor([0.7288, 0.4176, 0.8589])
tensor(0.4176)
0.4175570011138916


In [22]:
# Reshape with torch.view()

x= torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8) # the size -1 is inferred from otehr dimensions
# -f -1 Pytorch will automatically determine the necessary size
print(x.size(),y.size(),z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [26]:
#Numpy
#Converting a Torch to a NumPy array and vice versa

a = torch.ones(5)
print(a)

#torch to numpy with .numpy()

b = a.numpy()
print(b)
print(type(b))

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [27]:
# Careful : if the Tensor is on the CPU ( not the GPU),
# both objects will share the same memory location, so changing one
# will also change the other
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [28]:
#numpy to torch with .from_numpy(x)

import numpy as np

a = np.ones(5)
b = torch.from_numpy(a)
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [29]:
# again be careful when modifying

a +=1
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [ ]:
#by default all tensor are created on the CPU,
#but you can also move them to the GPU (only if its available )

if torch.cuda.is_available():
  device = torch.device("cuda")                  #a CUDA device object
  y = torch.ones_like(x,device = device)         # directly create a tensor on GPU
  x = x.to(device)                               # or just use strongs ' '.to("cuda")
  z = x + y
  # z = z.numpy() # not possible because numpy cannot handle GPU tensors
  # move to CPU again
  z.to("CPU")
  #z = z.numpy()